name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deply.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/astro-backend-cicd-role
          aws-region: eu-central-1

      - name: Backup current S3 files
        run: |
          export DATE=$(date +%Y-%m-%d-%H%M%S)
          aws s3 cp s3://astro-frontend-bucket/ s3://astro-frontend-bucket/backup/$DATE/ --recursive
        env:
          AWS_REGION: eu-central-1

      - name: Upload new build to S3
        run: |
          aws s3 sync frontend/dist s3://astro-frontend-bucket/ --delete
        env:
          AWS_REGION: eu-central-1